name: Claude Assistant

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-assistant:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body || github.event.issue.body || github.event.pull_request.body, '@claude') || contains(github.event.comment.body || github.event.issue.body || github.event.pull_request.body, 'claude')
    
    steps:
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: Configure specific tools
          allowed_tools: |
            view
            str_replace_editor
            bash
          # Optional: Add custom system prompt for your project
          system_prompt: |
            You are helping with the Claude Code Session Export tool.
            This tool exports Claude Code chat sessions with full metadata.
            Be helpful with troubleshooting export issues and explaining features.